### ISSUE TITLE
Crash when making a quest.

### ISSUE THREAD

**Issue by AnAwesomGuy** [FTBTeam/FTB-Library#31] opened 2021-06-06 13:27 UTC
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod version**
ftb-library-forge-1605.3.1-build.18.jar

**Forge / Fabric version, if applicable**
36.1.16

**Modpack (with version), if applicable**
custom

**If the issue is a crash; An external link to the crash report**
https://pastebin.com/wUNZ9TR7

**How to reproduce the issue**
create a quest

**Anything else we should know?**
also jei says that ftb lib not installed even though it is

**Comment by MaxNeedsSnacks** [comment] 2021-08-19 13:59
Duplicate of FTBTeam/FTB-Quests#602

**Comment by MaxNeedsSnacks** [comment] 2021-08-19 14:00
> also jei says that ftb lib not installed even though it is
Also this should no longer be happening hopefully, just keep all your mods up-to-date ^^

**Closed by MaxNeedsSnacks** 2021-08-19 13:59 UTC
Labels: bug
