### ISSUE TITLE
MC 1.16.5 Crash When opening FTB quests

### ISSUE THREAD

**Issue by litjohn50** [FTBTeam/FTB-Library#26] opened 2021-04-30 16:41 UTC
MC Version 1.16.5
FTB Library version: 1605.2.1.41-forge
FTB Quests Version: 1605.2.1-build.39-forge

Bug: Client Crash when trying create a new item quest and it opens the item gui.

Crash Log: https://gist.github.com/litjohn50/89b9470eb131b85750a3d9e4d48ef3f9

**Comment by MaxNeedsSnacks** [comment] 2021-08-19 13:56
Duplicate of https://github.com/FTBTeam/FTB-Quests/issues/602

**Closed by MaxNeedsSnacks** 2021-08-19 13:56 UTC
Labels: bug
