### ISSUE TITLE
[bug] Item Browser crashing client

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Library#32] opened 2021-07-20 18:44 UTC
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version** 
FTB Library, but we triggered it with FTB Quests
ftb library 1605.3.1-biuld.48
ftb quests forge 1605.3.3-build.39

**Forge / Fabric version, if applicable**
Forge 36.1.65

**Modpack (with version), if applicable**
World of Dragons 2 for 1.16.5, not yet released

**If the issue is a crash; An external link to the crash report**
https://gitlab.com/kreezxil/world-of-dragons-2/-/issues/120

**How to reproduce the issue**
*Please provide use with a step by step description*
The item browser to set required/reward/icons in the quest menu is glitched to be a small thing in the top left of the menu that doesn't show items.

**video showing the glitch and the resulting crash**

https://user-images.githubusercontent.com/3880072/126378413-9f7391ff-82fc-4dc8-b274-a00d04c2ecac.mp4

**Comment by kreezxil** [comment] 2021-07-20 19:13
Found a solution. It last worked on forge 36.1.62. So, I rolled back wala, the item browser works again. Seems a class got changed, but Forge team didn't update the class version. :(

**Comment by MaxNeedsSnacks** [comment] 2021-07-21 10:41
Duplicate of https://github.com/FTBTeam/FTB-Quests/issues/602

**Comment by MaxNeedsSnacks** [comment] 2021-07-21 10:42
For reference, this is some weird issue that *probably* has to do with classloading and / or garbage collection, we'll be looking into hopefully resolving it soon :/

**Closed by MaxNeedsSnacks** 2021-07-21 10:41 UTC
